services:
  h2db:
    image: oscarfonts/h2
    container_name: solin-h2
    ports:
      - "8082:81"
      - "9092:1521"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - solin-h2-data:/opt/h2-data

  api:
    build: .
    container_name: solin-api
    ports:
      - "8080:8080"
    depends_on:
      - h2db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: "jdbc:h2:tcp://h2db:1521/solin;AUTO_SERVER=TRUE;IFEXISTS=FALSE"
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

volumes:
  solin-h2-data:
